---
title: "Bayesian_Modelling_Analysis"
format: html
editor: visual
---

# Bayesian Modelling Analysis

**Packages**

```{r}


library(here)
library(dplyr)
library(ggplot2)
library(DFBA)

```

## **Model Outputs**

```{r}

carp_agg <- read.csv("Data_Outputs/Bayesian_Modelling/Carp/carp_agg_results.csv")
carp_agg_wo_parasites <- read.csv("Data_Outputs/Bayesian_Modelling/Carp/carp_agg_wo_parasites_results.csv")

carp_ls <- read.csv("Data_Outputs/Bayesian_Modelling/Carp/carp_ls_results.csv")
carp_ls_wo_parasites <- read.csv("Data_Outputs/Bayesian_Modelling/Carp/carp_ls_wo_parasites_results.csv")


qp_agg_results <- read.csv("Data_Outputs/Bayesian_Modelling/Quick_Pond/qp_agg_results.csv")
qp_agg_wo_parasites <- qp_agg_results %>% filter(web == "aggregated_wo_parasites")
qp_agg <- qp_agg_results %>% filter(web == "aggregated")
qp_ls_results <- read.csv("Data_Outputs/Bayesian_Modelling/Quick_Pond/qp_ls_results.csv")
qp_ls_wo_parasites <- qp_ls_results %>% filter(web == "life_stage_wo_parasites")
qp_ls <- qp_ls_results %>% filter(web == "life_stage")


ythan_with_parasites <- read.csv("Data_Outputs/Bayesian_Modelling/Ythan/ythan_with_parasites_concam_results.csv")
ythan_without_parasites <- read.csv("Data_Outputs/Bayesian_Modelling/Ythan/ythan_without_parasites_results.csv")

banda_with_parasites <- read.csv("Data_Outputs/Bayesian_Modelling/Banda/banda_with_parasites_concam_results.csv")
banda_without_parasites <- read.csv("Data_Outputs/Bayesian_Modelling/Banda/banda_without_parasites_results.csv")
```

**Significance Testing**

```{r}

set.seed(100)

t1 <- dfba_mann_whitney(
  E = carp_agg$extinction_mean, 
  C = carp_agg_wo_parasites$extinction_mean, 
  samples = 100000
)

t2 <- dfba_mann_whitney(
  E = carp_ls$extinction_mean, 
  C = carp_ls_wo_parasites$extinction_mean, 
  samples = 100000
)


t3 <- dfba_mann_whitney(
  E = qp_agg$extinction_mean, 
  C = qp_agg_wo_parasites$extinction_mean, 
  samples = 100000
)

t4 <- dfba_mann_whitney(
  E = qp_ls$extinction_mean, 
  C = qp_ls_wo_parasites$extinction_mean, 
  samples = 100000
)

t5 <- dfba_mann_whitney(
  E = carp_ls_wo_parasites$extinction_mean, 
  C = carp_agg_wo_parasites$extinction_mean, 
  samples = 100000
)


t6 <- dfba_mann_whitney(
  E = qp_ls_wo_parasites$extinction_mean, 
  C = qp_agg_wo_parasites$extinction_mean, 
  samples = 100000
)



```

**Comparing Parasitic & Non-Parasitic Taxa**

```{r}


qp_parasitic_species <- c(49:63)
qp_parasitic_nodes <- c(72:113)

carp_parasitic_species <- readRDS("Data_Outputs/carp_parasitic_species_ids.rds")
carp_parasitic_nodes <- readRDS("Data_Outputs/carp_parasitic_node_ids.rds")

ythan_parasites_species <- setdiff(ythan_with_parasites$NodeID, ythan_without_parasites$NodeID)
banda_parasites_species <- setdiff(banda_with_parasites$NodeID, banda_without_parasites$NodeID)


qp_agg_parasite_ext <- qp_agg %>% filter(NodeID %in% qp_parasitic_species) %>% 
  mutate(type = "qp_agg_parasite")
qp_agg_non_parasite_ext <- qp_agg %>% filter(!NodeID %in% qp_parasitic_species) %>%
  mutate(type = "qp_agg_non_parasite")

qp_ls_parasite_ext <- qp_ls %>% filter(NodeID %in% qp_parasitic_nodes) %>%
  mutate(type = "qp_ls_parasite")
qp_ls_non_parasite_ext <- qp_ls %>% filter(!NodeID %in% qp_parasitic_nodes) %>%
   mutate(type = "qp_ls_non_parasite")

carp_agg_parasite_ext <- carp_agg %>% filter(NodeID %in% carp_parasitic_species) %>% 
  mutate(type = "carp_agg_parasite")
carp_agg_non_parasite_ext <- carp_agg %>% filter(!NodeID %in% carp_parasitic_species) %>% 
  mutate(type = "carp_agg_non_parasite")
carp_ls_parasite_ext <- carp_ls %>% filter(NodeID %in% carp_parasitic_nodes) %>% 
  mutate(type = "carp_ls_parasite")
carp_ls_non_parasite_ext <- carp_ls %>% filter(!NodeID %in% carp_parasitic_nodes)  %>% 
  mutate(type = "carp_ls_non_parasite")

ythan_parasites_REMOVED <- ythan_with_parasites %>% 
  filter(!NodeID %in% ythan_parasites_species) %>% mutate(type = "non-parasites")
ythan_parasites_only <- ythan_with_parasites %>%
  filter(NodeID %in% ythan_parasites_species) %>% mutate(type = "parasites")


banda_parasites_REMOVED <- banda_with_parasites %>%
  filter(!NodeID %in% banda_parasites_species) %>% mutate(type = "non-parasites")
banda_parasites_only <- banda_with_parasites %>%
  filter(NodeID %in% banda_parasites_species) %>% mutate(type = "parasites")


qp_exts_separated <- bind_rows(
  qp_agg_parasite_ext,
  qp_agg_non_parasite_ext, 
  qp_ls_parasite_ext,
  qp_ls_non_parasite_ext)


carp_exts_separated <- bind_rows(
  carp_agg_parasite_ext,
  carp_agg_non_parasite_ext, 
  carp_ls_parasite_ext,
  carp_ls_non_parasite_ext)


ythan_exts_separated <- bind_rows(
  ythan_parasites_REMOVED, 
  ythan_parasites_only
)


banda_exts_separated <- bind_rows(
  banda_parasites_REMOVED, 
  banda_parasites_only
)



ggplot(qp_exts_separated,
       aes(x = type, y = extinction_mean, fill = type)) +
  geom_boxplot() +
  scale_fill_manual(
    values = c(
      "qp_agg_parasite" = "red",  
      "qp_agg_non_parasite" = "steelblue",
      "qp_ls_parasite"= "red", 
      "qp_ls_non_parasite" = "steelblue")
  ) +
  theme_bw() +
  labs(
    x = "Web Type",
    y = "Mean Extinction Probability"
  ) +
  ylim(0,1) +
  theme(legend.position = "none") +
   scale_x_discrete(
    labels = c(
      "qp_agg_parasite" = "Parasites\n (Agg)",
      "qp_agg_non_parasite" = "Non-Parasites\n (Agg)",
      "qp_ls_parasite" = "Parasites\n (LS)",
      "qp_ls_non_parasite" = "Non-Parasites\n (LS)"
    )) +
    theme(
  axis.title = element_text(size = 15, face = "bold"),
  axis.text.y = element_text(size = 20, face = "bold"),
  axis.text.x = element_text(
    size = 15,
    face = "bold",
    angle = 45,
    hjust = 1
  ),
  axis.title.x = element_blank()
)


ggplot(carp_exts_separated,
       aes(x = type, y = extinction_mean, fill = type)) +
  geom_boxplot() +
  scale_fill_manual(
    values = c(
      "carp_agg_parasite" = "red",  
      "carp_agg_non_parasite" = "steelblue",
      "carp_ls_parasite"= "red", 
      "carp_ls_non_parasite" = "steelblue")
  ) +
  theme_bw() +
  labs(
    x = "Web Type",
    y = "Mean Extinction Probability"
  ) +
  ylim(0,1) +
  theme(legend.position = "none") +
   scale_x_discrete(
    labels = c(
      "carp_agg_parasite" = "Parasites\n (Agg)",
      "carp_agg_non_parasite" = "Non-Parasites\n (Agg)",
      "carp_ls_parasite" = "Parasites\n (LS)",
      "carp_ls_non_parasite" = "Non-Parasites\n (LS)"
    )) +
    theme(
  axis.title = element_text(size = 15, face = "bold"),
  axis.text.y = element_text(size = 20, face = "bold"),
  axis.text.x = element_text(
    size = 15,
    face = "bold",
    angle = 45,
    hjust = 1
  ),
  axis.title.x = element_blank()
)




ggplot(ythan_exts_separated, 
       aes(x = type, y = extinction_mean, fill = type)) +
  geom_boxplot() +
  scale_fill_manual(
    values = c(
      "parasites" = "red",  
      "non-parasites" = "steelblue")
  ) +
  theme_bw() +
  labs(
    x = "Group",
    y = "Mean Extinction Probability"
  ) +
  ylim(0,1) +
  theme(legend.position = "none") +
   scale_x_discrete(
    labels = c(
      "parasites" = "Parasites",
      "non-parasites" = "Non-Parasites"
    )) +
    theme(
    axis.title = element_text(size = 15, face = "bold"),  
    axis.text = element_text(size = 20, face = "bold"),
    axis.title.x = element_blank()
  )

ggplot(banda_exts_separated, 
       aes(x = type, y = extinction_mean, fill = type)) +
  geom_boxplot() +
  scale_fill_manual(
    values = c(
      "parasites" = "red",  
      "non-parasites" = "steelblue")
  ) +
  theme_bw() +
  labs(
    x = "Group",
    y = "Mean Extinction Probability"
  ) +
  ylim(0,1) +
  theme(legend.position = "none") +
   scale_x_discrete(
    labels = c(
      "parasites" = "Parasites",
      "non-parasites" = "Non-Parasites"
    )) +
    theme(
    axis.title = element_text(size = 15, face = "bold"),  
    axis.text = element_text(size = 20, face = "bold"),
    axis.title.x = element_blank()
  )



wilcox.test(carp_agg_parasite_ext$extinction_mean, carp_agg_non_parasite_ext$extinction_mean)
wilcox.test(carp_ls_parasite_ext$extinction_mean, carp_ls_non_parasite_ext$extinction_mean)


t7 <- dfba_mann_whitney(
  E = ythan_parasites_only$extinction_mean, 
  C = ythan_parasites_REMOVED$extinction_mean, 
  samples = 100000
)

t8 <- dfba_mann_whitney(
  E = banda_parasites_only$extinction_mean, 
  C = banda_parasites_REMOVED$extinction_mean, 
  samples = 100000
)

t9 <- dfba_mann_whitney(
  E = qp_agg_parasite_ext$extinction_mean, 
  C = qp_agg_non_parasite_ext$extinction_mean, 
  samples = 100000
)

t10 <- dfba_mann_whitney(
  E = qp_ls_parasite_ext$extinction_mean, 
  C = qp_ls_non_parasite_ext$extinction_mean, 
  samples = 100000
)

t11 <- dfba_mann_whitney(
  E = carp_agg_parasite_ext$extinction_mean, 
  C = carp_agg_non_parasite_ext$extinction_mean, 
  samples = 100000
)

t12 <- dfba_mann_whitney(
  E = carp_ls_parasite_ext$extinction_mean, 
  C = carp_ls_non_parasite_ext$extinction_mean, 
  samples = 100000
)


```

```{r}

qp_agg_parasite_species <- setdiff(qp_agg$NodeID, qp_agg_wo_parasites$NodeID)
qp_ls_parasite_nodes <- setdiff(qp_ls$NodeID, qp_ls_wo_parasites$NodeID)

qp_agg_parasites_REMOVED <- qp_agg %>% filter(!NodeID %in% qp_agg_parasite_species)
qp_ls_parasites_REMOVED <- qp_ls %>% filter(!NodeID %in% qp_ls_parasite_nodes)


qp_agg_comparison <- data.frame(without_parasites = qp_agg_wo_parasites$extinction_mean,
                          with_parasites = qp_agg_parasites_REMOVED$extinction_mean)

qp_agg_comparison <- qp_agg_comparison %>%
  dplyr::mutate(
    position = case_when(
      with_parasites > without_parasites ~ "Above",
      with_parasites < without_parasites ~ "Below",
      TRUE ~ "Same"
    )
  )


qp_ls_comparison <- data.frame(without_parasites = qp_ls_wo_parasites$extinction_mean,
                          with_parasites = qp_ls_parasites_REMOVED$extinction_mean)

qp_ls_comparison <- qp_ls_comparison %>%
  dplyr::mutate(position = case_when(
    with_parasites > without_parasites ~ "Above",
    with_parasites < without_parasites ~ "Below", 
    TRUE ~ "Same"
    )
  )


ythan_parasites_species <- setdiff(ythan_with_parasites$NodeID, ythan_without_parasites$NodeID)
banda_parasites_species <- setdiff(banda_with_parasites$NodeID, banda_without_parasites$NodeID)

ythan_parasites_results <- ythan_with_parasites %>% filter(NodeID %in% ythan_parasites_species)
banda_parasites_results <- banda_with_parasites %>% filter(NodeID %in% banda_parasites_species)



ggplot(qp_agg_comparison,
       aes(without_parasites, with_parasites, colour = position)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_abline(
    slope = 1,
    intercept = 0,
    colour = "black",
    linewidth = 1
  ) +
  scale_colour_manual(
    values = c(
      "Above" = "steelblue",
      "Below" = "red", 
      "Same" = "grey50"
    )
  ) +
  labs(
    x = "Probability Extinction (Without Parasites)",
    y = "Probability Extinction (With Parasites)"
  ) +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 15, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")
  )


ggplot(qp_ls_comparison, 
                           aes(without_parasites, with_parasites, colour = position)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_abline(
    slope = 1,
    intercept = 0,
    colour = "black",
    linewidth = 1
  ) +
  scale_colour_manual(
    values = c(
      "Above" = "steelblue",
      "Below" = "red",
      "Same" = "grey50"
    )
  ) +
  labs(
    x = "Probability Extinction (Without Parasites)",
    y = "Probability Extinction (With Parasites)"
  ) +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 15, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")
  )



ythan_parasites_comparison <- ggplot()


```

```{r}

carp_agg_parasite_species <- setdiff(carp_agg$NodeID, carp_agg_wo_parasites$NodeID)
carp_ls_parasite_nodes <- setdiff(carp_ls$NodeID, carp_ls_wo_parasites$NodeID)


carp_agg_parasites_REMOVED <- carp_agg %>% filter(!NodeID %in% carp_agg_parasite_species)
carp_ls_parasites_REMOVED <- carp_ls %>% filter(!NodeID %in% carp_ls_parasite_nodes)


carp_agg_comparison <- data.frame(without_parasites = carp_agg_wo_parasites$extinction_mean,
                          with_parasites = carp_agg_parasites_REMOVED$extinction_mean)

carp_agg_comparison <- carp_agg_comparison %>%
  dplyr::mutate(
    position = case_when(
      with_parasites > without_parasites ~ "Above",
      with_parasites < without_parasites ~ "Below",
      TRUE ~ "Same"
    )
  )

carp_ls_comparison <- data.frame(without_parasites = carp_ls_wo_parasites$extinction_mean,
                          with_parasites = carp_ls_parasites_REMOVED$extinction_mean)

carp_ls_comparison <- carp_ls_comparison %>%
  dplyr::mutate(
    position = case_when(
      with_parasites > without_parasites ~ "Above",
      with_parasites < without_parasites ~ "Below",
      TRUE ~ "Same"
    )
  )


ggplot(carp_agg_comparison, 
       aes(without_parasites, with_parasites, colour = position)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_abline(
    slope = 1,
    intercept = 0,
    colour = "black",
    linewidth = 1
  ) +
  scale_colour_manual(
    values = c(
      "Above" = "steelblue",
      "Below" = "red",
      "Same" = "grey50"
    )
  ) +
  labs(
    x = "Probability Extinction (Without Parasites)",
    y = "Probability Extinction (With Parasites)"
  ) +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 15, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")
  )


ggplot(carp_ls_comparison, 
       aes(without_parasites, with_parasites, colour = position)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_abline(
    slope = 1,
    intercept = 0,
    colour = "black",
    linewidth = 1
  ) +
  scale_colour_manual(
    values = c(
      "Above" = "steelblue",
      "Below" = "red",
      "Same" = "grey50"
    )
  ) +
  labs(
    x = "Probability Extinction (Without Parasites)",
    y = "Probability Extinction (With Parasites)"
  ) +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 15, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")
  )
```

```{r}

ythan_comparison <- data.frame(with_parasites = ythan_parasites_REMOVED$extinction_mean, 
                               without_parasites = ythan_without_parasites$extinction_mean)

ythan_comparison <- ythan_comparison %>%
  dplyr::mutate(
    position = case_when(
      with_parasites > without_parasites ~ "Above",
      with_parasites < without_parasites ~ "Below",
      TRUE ~ "Same"
    )
  )

ggplot(ythan_comparison, 
       aes(without_parasites, with_parasites, colour = position)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_abline(
    slope = 1,
    intercept = 0,
    colour = "black",
    linewidth = 1
  ) +
  scale_colour_manual(
    values = c(
      "Above" = "steelblue",
      "Below" = "red",
      "Same" = "grey50"
    )
  ) +
  labs(
    x = "Probability Extinction (Without Parasites)",
    y = "Probability Extinction (With Parasites)"
  ) +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 15, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")
  )


```

```{r}


banda_comparison <- data.frame(with_parasites = banda_parasites_REMOVED$extinction_mean, 
                               without_parasites = banda_without_parasites$extinction_mean)

banda_comparison <- banda_comparison %>%
  dplyr::mutate(
    position = case_when(
      with_parasites > without_parasites ~ "Above",
      with_parasites < without_parasites ~ "Below",
      TRUE ~ "Same"
    )
  )

ggplot(banda_comparison, 
       aes(without_parasites, with_parasites, colour = position)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_abline(
    slope = 1,
    intercept = 0,
    colour = "black",
    linewidth = 1
  ) +
  scale_colour_manual(
    values = c(
      "Above" = "steelblue",
      "Below" = "red",
      "Same" = "grey50"
    )
  ) +
  labs(
    x = "Probability Extinction (Without Parasites)",
    y = "Probability Extinction (With Parasites)"
  ) +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 15, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")
  )



```

```{r}



t13 <- dfba_mann_whitney(
  E = carp_agg_parasite_ext$extinction_mean, 
  C = carp_ls_parasite_ext$extinction_mean, 
  samples = 100000
)

t14 <- dfba_mann_whitney(
  E = qp_agg_parasite_ext$extinction_mean, 
  C = qp_ls_parasite_ext$extinction_mean, 
  samples = 100000
)




```
